### ISSUE TITLE
Game crash when multiple trains at same station

### ISSUE THREAD

**Issue by ghost** [SEPRFVS/FVS4#16]
Place a train at a station as Player 1. Click End turn. Place a train to the same station as Player 2. Try to click on your train. => Game closes.

Stack trace:
AL lib: (WW) FreeDevice: (0x7fbd022f1e00) Deleting 8 Buffer(s)
Exception in thread "LWJGL Application" java.lang.NullPointerException
    at fvs.taxe.dialog.DialogStationMultitrain.trainString(DialogStationMultitrain.java:39)
    at fvs.taxe.dialog.DialogStationMultitrain.getTrainFromString(DialogStationMultitrain.java:53)
    at fvs.taxe.dialog.DialogStationMultitrain.result(DialogStationMultitrain.java:71)
    at com.badlogic.gdx.scenes.scene2d.ui.Dialog$2.changed(Dialog.java:91)
    at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
    at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
    at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
    at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:116)
    at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:90)
    at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
    at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
    at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:348)
    at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:306)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:206)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by ghost** [comment]
Critical

**Comment by tylrbvn** [comment]
Closed in 3b6e739
